---
- name: Gather Root Disk Information and CPU and RAM information
  hosts: all
  become: yes
  tasks:
    - name: Gather Facts
      ansible.builtin.setup:
        gather_subset: hardware

    - name: Display Root Disk Size
      debug:
        msg: "Server {{ inventory_hostname }} - Root Disk Size: {{ ansible_facts.devices[item].size }}"
      loop: "{{ ansible_facts.devices.keys() }}"
      when: "('sd' in item or 'vd' in item or 'nvme' in item) and ansible_facts.devices[item].partitions"
      register: root_disk_info
      tags: root_disk

    - name: Get CPU and RAM information from Ubuntu server
      debug:
              msg: "Total CPU count: {{ ansible_processor_count }} , Total RAM size: {{ (ansible_memtotal_mb / 1024) | round(2) }} GB"
        
