---
- name: Gather Hardware Information
  hosts: all
  become: yes
  tasks:
    - name: Get CPU Information
      ansible.builtin.command: "nproc"
      register: cpu_count

    - name: Get RAM Information
      ansible.builtin.shell: "free -h | awk '/^Mem:/{print $2}'"
      register: ram_size

    - name: Get Root Disk Size
      ansible.builtin.shell: "df -h / | awk 'NR==2{print $2}'"
      register: root_disk_size

    - name: Display Hardware Information
      ansible.builtin.debug:
        msg: "Server {{ inventory_hostname }} - Number of CPUs: {{ cpu_count.stdout }}, Total RAM: {{ ram_size.stdout }}, Root Disk Size: {{ root_disk_size.stdout }}"
